## **A/B Testing**

* A/B testing is used to compare two versions of an element to see which one perfoms better

In [63]:
# import necessary libraries
import pandas as pd
from scipy import stats
import statsmodels.api as sm
import matplotlib.pyplot as plt
import numpy as np

In [64]:
homepage_data=pd.read_csv(r'homepage_actions.csv')
homepage_data.head()

                    timestamp      id       group action
0  2016-09-24 17:42:27.839496  804196  experiment   view
1  2016-09-24 19:19:03.542569  434745  experiment   view
2  2016-09-24 19:36:00.944135  507599  experiment   view
3  2016-09-24 19:59:02.646620  671993     control   view
4  2016-09-24 20:26:14.466886  536734  experiment   view

In [65]:
experimental_group=homepage_data[homepage_data["group"]=="experiment"]
experimental_group.head()

                    timestamp      id       group action
0  2016-09-24 17:42:27.839496  804196  experiment   view
1  2016-09-24 19:19:03.542569  434745  experiment   view
2  2016-09-24 19:36:00.944135  507599  experiment   view
4  2016-09-24 20:26:14.466886  536734  experiment   view
5  2016-09-24 20:32:25.712659  681598  experiment   view

In [66]:
control_group=homepage_data[homepage_data["group"]=="control"]
control_group.head()

                     timestamp      id    group action
3   2016-09-24 19:59:02.646620  671993  control   view
9   2016-09-24 21:00:12.278374  560027  control   view
23  2016-09-25 00:25:14.141290  281985  control   view
24  2016-09-25 01:14:48.603202  407864  control   view
25  2016-09-25 02:16:11.046654  342984  control   view

In [67]:
click_action_control=control_group['action'].value_counts()
click_action_control

action
view     3332
click     932
Name: count, dtype: int64

* Based on the data what kind of distribution is this?
* how do we calculate the outcome of binomial distribution=n*p

In [68]:
experimental_views=(experimental_group['action']=='view').sum()
experimental_views

np.int64(2996)

In [69]:
experimental_clicks=(experimental_group['action']=='click').sum()
experimental_clicks

np.int64(928)

In [70]:
experimental_ctr=(experimental_clicks/experimental_views)
experimental_ctr

np.float64(0.3097463284379172)

In [71]:
control_views=(control_group['action']=='view').sum()
control_views

np.int64(3332)

In [72]:
control_clicks=(control_group['action']=='click').sum()
control_clicks

np.int64(932)

In [73]:
control_ctr=(control_clicks/control_views)
control_ctr

np.float64(0.2797118847539016)

In [74]:
probability=(experimental_clicks+control_clicks)/(experimental_views+control_views)
probability

np.float64(0.2939317319848293)

In [75]:
e_sum=experimental_group['action'].count()
e_sum

np.int64(3924)

In [76]:
experimental_mean=(experimental_views*experimental_ctr)
experimental_mean

np.float64(928.0)

In [77]:
control_mean=(control_views*control_ctr)
control_mean

np.float64(932.0)

In [78]:
pooled_std=np.sqrt((control_views*probability)*(1-probability)*((1/control_views)+(1/experimental_views)))
pooled_std

np.float64(0.6620776303079153)

In [79]:
z_statistic=(experimental_ctr-control_ctr)/(pooled_std)
z_statistic

np.float64(0.04536393061648585)

In [80]:
cdf=stats.norm.cdf(z_statistic)
cdf

np.float64(0.5180913847135817)

In [81]:
p_value=(1-cdf)
p_value

np.float64(0.48190861528641826)